import 'dart:io';
import 'package:car_rental_customerPanel/Portal/Customer/MyDetails/MeDetailsController.dart';
import 'package:car_rental_customerPanel/Portal/Customer/MyDetails/ReusableWidget/HeaderWebDetailWidget.dart';
import 'package:car_rental_customerPanel/Resources/AppSizes.dart';
import 'package:car_rental_customerPanel/Resources/Color.dart';
import 'package:car_rental_customerPanel/Resources/IconString.dart';
import 'package:car_rental_customerPanel/Resources/ImageString.dart';
import 'package:car_rental_customerPanel/Resources/TextString.dart';
import 'package:car_rental_customerPanel/Resources/TextTheme.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:go_router/go_router.dart';


class MyDetails extends StatelessWidget {
  const MyDetails({super.key});

  @override
  Widget build(BuildContext context) {
    final controller = Get.put(MyDetailController());

    return Scaffold(
      backgroundColor: AppColors.backgroundOfScreenColor,
      body: SafeArea(
        child: Column(
          children: [
            HeaderWebDetailWidget(
              mainTitle: TextString.myDetailsHeader,
              showBack: true,
              showSettings: true,
              showNotification: true,
              showProfile: true,
              onBackPressed: () {
                if (Navigator.canPop(context)) {
                  context.pop();
                } else {
                  context.go('/AddDetailScreen');
                }
              },
            ),
            Expanded(
              child: SingleChildScrollView(
                physics: const BouncingScrollPhysics(),
                padding: EdgeInsets.symmetric(
                  horizontal: AppSizes.horizontalPadding(context),
                  vertical: 20,
                ),
                child: Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Obx(() {
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildProfileHeaderSection(context, controller),
                        const SizedBox(height: 24),
                        if (controller.isSubmitted.value && !controller.isApproved.value) ...[
                          _buildPendingBanner(context),
                          const SizedBox(height: 20),
                        ],
                        if (controller.isApproved.value) ...[
                          _buildAdminNoteBanner(context, controller),
                          const SizedBox(height: 20),
                        ],
                        _buildPersonalInfoSection(context, controller),
                        const SizedBox(height: 20),
                        _buildLicenseDetailsSection(context, controller),
                        const SizedBox(height: 20),
                        _buildDocumentsSection(context, controller),
                        if (controller.isSubmitted.value) ...[
                          const SizedBox(height: 20),
                          _buildAutoGeneratedCredentialsSection(context, controller),
                        ],
                      ],
                    );
                  }),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

   /// ------------- Extra Widget ----------------- ///

  // Status Banner
  Widget _buildPendingBanner(BuildContext context) {
    return Container(
      width: double.infinity,
      padding:  EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color:  AppColors.emojiBackground,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: AppColors.pendingColor),
      ),
      child: Row(
        children:  [
          Icon(Icons.hourglass_empty_rounded, color: AppColors.reviewColor, size: 20),
          SizedBox(width: 10),
          Expanded(
            child: Text(
              TextString.pendingBannerText,
              style: TTextTheme.btnTwo(context).copyWith(
                color: AppColors.blackColor,
                fontSize: 13,
                fontWeight: FontWeight.w400,
              ),
            )
          ),
        ],
      ),
    );
  }

   // Note Banner
  Widget _buildAdminNoteBanner(BuildContext context, MyDetailController controller) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.signaturePadColor,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color:  AppColors.noteBanner),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            TextString.noteTitle,
            style: TTextTheme.titleSix(context).copyWith(
              color: AppColors.completedColor,
              fontWeight: FontWeight.bold,
              fontSize: 14,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            controller.adminNote.value,
            style: TTextTheme.btnTwo(context).copyWith(
              color: AppColors.blackColor,
              fontSize: 13,
            ),
          ),
        ],
      ),
    );
  }

  // Profile Header
  Widget _buildProfileHeaderSection(BuildContext context, MyDetailController controller) {
    return LayoutBuilder(
      builder: (context, constraints) {
        bool isCompact = constraints.maxWidth < 650;
        final bool submitted = controller.isSubmitted.value;

        String fullName = submitted
            ? "${controller.givenNameController2.text} ${controller.surnameController2.text}".trim()
            : TextString.defaultDriverName;
        String email = submitted ? controller.emailController2.text : TextString.defaultRole;

        Widget profileImage = Container(
          width: 100,
          height: 100,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: AppColors.primaryColor.withOpacity(0.4), width: 1.5),
            color: Colors.white,
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(10),
            child: controller.profileImage2.value != null
                ? Image.file(
              File(controller.profileImage2.value!.path!),
              fit: BoxFit.cover,
            )
                : Image.asset(
              ImageString.userImage,
              fit: BoxFit.cover,
              errorBuilder: (context, error, stackTrace) => Container(color: AppColors.secondaryColor),
            ),
          ),
        );

        Widget userDetails = Column(
          crossAxisAlignment: isCompact ? CrossAxisAlignment.center : CrossAxisAlignment.start,
          children: [
            Text(
              fullName.isNotEmpty ? fullName : TextString.defaultDriverName,
              style: TTextTheme.h1Style(context).copyWith(fontWeight: FontWeight.bold, fontSize: 26),
            ),
            const SizedBox(height: 4),
            Text(
              email.isNotEmpty ? email : TextString.defaultRole,
              style: TTextTheme.titleDriver(context).copyWith(color: AppColors.tertiaryTextColor, fontSize: 14),
            ),
          ],
        );
        Widget actionButton = submitted
            ? OutlinedButton.icon(
          onPressed: () {
            _showApproveRequestDialog(context);
          },
          icon: Image.asset(
            IconString.editIcon,
            width: 18,
            height: 18,
            color: AppColors.primaryColor,
            errorBuilder: (context, error, stackTrace) =>
            const Icon(Icons.edit_square, size: 18, color: AppColors.primaryColor),
          ),
          label: Text(
            TextString.editRequestBtn,
            style: TTextTheme.btnTwo(context).copyWith(
              color: AppColors.primaryColor,
              fontWeight: FontWeight.w400,
              fontSize: 14,
            ),
          ),
          style: OutlinedButton.styleFrom(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
            side: const BorderSide(color: AppColors.primaryColor, width: 1.2),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          ),
        )
            : ElevatedButton.icon(
          onPressed: () {
            context.go('/AddDetailScreen', extra: {"hideMobileAppBar": true});
          },
          icon: Image.asset(
            IconString.submitDetail,
            width: 18,
            height: 18,
            color: Colors.white,
            errorBuilder: (context, error, stackTrace) =>
            const Icon(Icons.assignment_outlined, size: 18, color: Colors.white),
          ),
          label: Text(
            TextString.submitDetailsBtn,
            style: TTextTheme.btnTwo(context).copyWith(
              color: Colors.white,
              fontWeight: FontWeight.w400,
              fontSize: 14,
            ),
          ),
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.primaryColor,
            elevation: 0,
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          ),
        );

        if (isCompact) {
          return Column(
            children: [
              Align(alignment: Alignment.centerRight, child: actionButton),
              const SizedBox(height: 16),
              profileImage,
              const SizedBox(height: 12),
              userDetails,
            ],
          );
        }

        return Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            profileImage,
            const SizedBox(width: 24),
            Expanded(child: userDetails),
            actionButton,
          ],
        );
      },
    );
  }

  // Personal Info Section
  Widget _buildPersonalInfoSection(BuildContext context, MyDetailController controller) {
    final bool submitted = controller.isSubmitted.value;

    return _buildBorderedContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            TextString.personalTitle,
            style: TTextTheme.titleSix(context).copyWith(
              fontWeight: FontWeight.w600,
              color: AppColors.secondTextColor,
              fontSize: 15,
            ),
          ),
          const SizedBox(height: 20),
          LayoutBuilder(
            builder: (context, constraints) {
              final double width = constraints.maxWidth;
              int columns = width < 600 ? 1 : (width < 850 ? 2 : (width < 1100 ? 3 : 5));
              const double spacing = 16.0;
              final double itemWidth = (width - (spacing * (columns - 1))) / columns;

              return Wrap(
                spacing: spacing,
                runSpacing: 20,
                children: [
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.sms,
                      TextString.emailLabel,
                      submitted ? controller.emailController2.text : TextString.dummyEmailPlaceholder,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.call,
                      TextString.contactNumLabel,
                      submitted ? controller.phoneController2.text : TextString.dummyPhonePlaceholder,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.location,
                      TextString.addressLabel,
                      submitted ? controller.addressController2.text : TextString.dummyAddressPlaceholder,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.birthIcon,
                      TextString.dobLabel,
                      submitted ? controller.dobController2.text : TextString.dummyDobPlaceholder,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.nidIcon,
                      TextString.nidLabel,
                      submitted ? controller.nidController2.text : TextString.dummyNidPlaceholder,
                    ),
                  ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }

  // License Detail Section
  Widget _buildLicenseDetailsSection(BuildContext context, MyDetailController controller) {
    final bool submitted = controller.isSubmitted.value;

    return _buildBorderedContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            TextString.licenseDetailScreen,
            style: TTextTheme.titleSix(context).copyWith(
              fontWeight: FontWeight.w600,
              color: AppColors.secondTextColor,
              fontSize: 15,
            ),
          ),
          const SizedBox(height: 20),
          LayoutBuilder(
            builder: (context, constraints) {
              final double width = constraints.maxWidth;
              int columns = width < 550 ? 1 : (width < 900 ? 2 : 4);
              const double spacing = 16.0;
              final double itemWidth = (width - (spacing * (columns - 1))) / columns;

              return Wrap(
                spacing: spacing,
                runSpacing: 20,
                children: [
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.licenseName,
                      TextString.licenseNameLabel,
                      submitted ? controller.licenseNameController2.text : TextString.dummyLicenseNamePlaceholder,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.licenseNo,
                      TextString.licenseNumLabel,
                      submitted ? controller.licenseNumberController2.text : TextString.dummyPhonePlaceholder,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.licenseCard,
                      TextString.cardNumberDetail,
                      submitted ? controller.licenseCardNumberController2.text : TextString.dummyPhonePlaceholder,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItem(
                      context,
                      IconString.expiryDate,
                      TextString.expiryDateLabel,
                      submitted ? controller.ccExpiryController2.text : TextString.expiryDateVal,
                    ),
                  ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }

  // Document Section
  Widget _buildDocumentsSection(BuildContext context, MyDetailController controller) {
    return _buildBorderedContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            TextString.customerDocumentDetails,
            style: TTextTheme.titleSix(context).copyWith(
              fontWeight: FontWeight.w600,
              fontSize: 15,
              color: AppColors.secondTextColor,
            ),
          ),
          const SizedBox(height: 20),
          Obx(() {
            final List<Map<String, dynamic>> docs = controller.documentsList.value;

            return LayoutBuilder(
              builder: (context, constraints) {
                final double width = constraints.maxWidth;
                int columns = width < 600 ? 1 : (width < 950 ? 2 : 3);
                const double spacing = 16.0;
                final double itemWidth = (width - (spacing * (columns - 1))) / columns;

                return Wrap(
                  spacing: spacing,
                  runSpacing: 16,
                  children: docs.map((doc) {
                    final String title = (doc["title"] ?? TextString.dummyDocTitlePlaceholder) as String;
                    final DocumentHolder? holder = doc["holder"] as DocumentHolder?;
                    final String status = holder?.name ?? (doc["status"] as String? ?? TextString.dummyDocStatusPlaceholder);

                    return SizedBox(
                      width: itemWidth,
                      child: _documentCardBox(
                        context,
                        title,
                        status,
                        onView: () => controller.handleDynamicView(context, doc),
                      ),
                    );
                  }).toList(),
                );
              },
            );
          }),
        ],
      ),
    );
  }


  Widget _documentCardBox(BuildContext context, String label, String status, {required VoidCallback onView}) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Container(
          width: 40,
          height: 40,
          decoration: BoxDecoration(
            color: AppColors.secondaryColor,
            borderRadius: BorderRadius.circular(8),
          ),
          child: const Icon(Icons.insert_drive_file_outlined, size: 20, color: AppColors.textColor),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                label,
                style: TTextTheme.titleFour(context).copyWith(
                  color: AppColors.tertiaryTextColor,
                  fontSize: 12,
                  fontWeight: FontWeight.w400,
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
              const SizedBox(height: 2),
              Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Flexible(
                    child: Text(
                      status,
                      style: TTextTheme.titleseven(context).copyWith(
                        color: AppColors.textColor,
                        fontWeight: FontWeight.bold,
                        fontSize: 13,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                  const SizedBox(width: 6),
                  InkWell(
                    onTap: onView,
                    borderRadius: BorderRadius.circular(12),
                    child: const Icon(Icons.remove_red_eye_outlined, size: 18, color: AppColors.textColor),
                  ),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildBorderedContainer({required Widget child}) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppColors.sideBoxesColor, width: 1),
      ),
      child: child,
    );
  }

  Widget _responsiveInfoItem(BuildContext context, String iconPath, String label, String value) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Container(
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            color: AppColors.secondaryColor,
            borderRadius: BorderRadius.circular(10),
          ),
          child: Image.asset(
            iconPath,
            width: 18,
            height: 18,
            color: AppColors.textColor,
            errorBuilder: (context, error, stackTrace) => const Icon(Icons.info_outline, size: 18, color: AppColors.textColor),
          ),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                label,
                style: TTextTheme.titleFour(context).copyWith(
                  color: AppColors.tertiaryTextColor,
                  fontSize: 12,
                ),
              ),
              const SizedBox(height: 2),
              Text(
                value,
                style: TTextTheme.titleseven(context).copyWith(
                  fontWeight: FontWeight.bold,
                  color: AppColors.textColor,
                  fontSize: 13,
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _responsiveInfoItemWithIcon(BuildContext context, IconData icon, String label, String value) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Container(
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            color: AppColors.secondaryColor,
            borderRadius: BorderRadius.circular(10),
          ),
          child: Icon(icon, size: 18, color: AppColors.textColor),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                label,
                style: TTextTheme.titleFour(context).copyWith(
                  color: AppColors.tertiaryTextColor,
                  fontSize: 12,
                ),
              ),
              const SizedBox(height: 2),
              Text(
                value,
                style: TTextTheme.titleseven(context).copyWith(
                  fontWeight: FontWeight.bold,
                  color: AppColors.textColor,
                  fontSize: 13,
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ],
          ),
        ),
      ],
    );
  }

  // Auto Generated Fields
  Widget _buildAutoGeneratedCredentialsSection(BuildContext context, MyDetailController controller) {
    return _buildBorderedContainer(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            TextString.autoGeneratedCredentials,
            style: TTextTheme.titleSix(context).copyWith(
              fontWeight: FontWeight.w600,
              fontSize: 15,
              color: AppColors.secondTextColor,
            ),
          ),
          const SizedBox(height: 20),
          LayoutBuilder(
            builder: (context, constraints) {
              final double width = constraints.maxWidth;
              int columns = width < 600 ? 1 : 2;
              const double spacing = 16.0;
              final double itemWidth = (width - (spacing * (columns - 1))) / columns;

              return Wrap(
                spacing: spacing,
                runSpacing: 20,
                children: [
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItemWithIcon(
                      context,
                      Icons.person_outline_rounded,
                      TextString.userNameLabel,
                      controller.userNameController.text.isNotEmpty
                          ? controller.userNameController.text
                          : TextString.defaultUserName,
                    ),
                  ),
                  SizedBox(
                    width: itemWidth,
                    child: _responsiveInfoItemWithIcon(
                      context,
                      Icons.lock_outline_rounded,
                      TextString.passwordLabel,
                      controller.passwordController.text.isNotEmpty
                          ? controller.passwordController.text
                          : TextString.defaultPassword,
                    ),
                  ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }


   /// Dialogs
  void _showApproveRequestDialog(BuildContext context) {
    final double screenWidth = MediaQuery.of(context).size.width;
    final bool isMobile = screenWidth < 600;

    showDialog(
      context: context,
      barrierDismissible: true,
      builder: (BuildContext context) {
        return Dialog(
          insetPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          backgroundColor: Colors.white,
          child: Container(
            constraints: const BoxConstraints(maxWidth: 480),
            padding: EdgeInsets.all(isMobile ? 16 : 24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Align(
                  alignment: Alignment.topRight,
                  child: GestureDetector(
                    onTap: () => Navigator.of(context).pop(),
                    child: Container(
                      padding: const EdgeInsets.all(4),
                      decoration: const BoxDecoration(
                        color: AppColors.secondaryColor,
                        shape: BoxShape.circle,
                      ),
                      child: const Icon(Icons.close, size: 16, color: AppColors.blackColor),
                    ),
                  ),
                ),

                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: 48,
                      height: 48,
                      decoration: BoxDecoration(
                        color: AppColors.emojiBackground,
                        borderRadius: BorderRadius.circular(12),
                      ),
                      alignment: Alignment.center,
                      child: const Text('🤨', style: TextStyle(fontSize: 24)),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "Need To Edit Your Details",
                            style: TTextTheme.h13Style(context).copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.textColor,
                            ),
                          ),
                          const SizedBox(height: 6),
                          Text(
                            "Your details have already been submitted. To make changes, you need to send an edit request to the admin. Once approved, you’ll be able to update your information. you are only able to edit your information once",
                            style: TTextTheme.bodyRegular14(context).copyWith(
                              color: AppColors.secondTextColor,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),
                Row(
                  children: [
                    Expanded(
                      child: SizedBox(
                        height: 42,
                        child: OutlinedButton(
                          style: OutlinedButton.styleFrom(
                            padding: EdgeInsets.zero,
                            side: const BorderSide(color: AppColors.primaryColor, width: 1.2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          onPressed: () {
                            Navigator.of(context).pop();

                          },
                          child: FittedBox(
                            fit: BoxFit.scaleDown,
                            child: Text(
                              'Save',
                              style: TTextTheme.btnSavePrimary(context),
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: SizedBox(
                        height: 42,
                        child: ElevatedButton(
                          style: ElevatedButton.styleFrom(
                            padding: EdgeInsets.zero,
                            backgroundColor: AppColors.primaryColor,
                            elevation: 0,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          onPressed: () =>{
                            Navigator.of(context).pop(),
                            _showSuccessDialog(context)
                          },
                          child: FittedBox(
                            fit: BoxFit.scaleDown,
                            child: Text(
                              "Request Edit",
                              style: TTextTheme.btnSave(context),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        );
      },
    );
  }
  void _showSuccessDialog(BuildContext context) {
    final double screenWidth = MediaQuery.of(context).size.width;
    final bool isMobile = screenWidth < 600;

    showDialog(
      context: context,
      barrierDismissible: true,
      builder: (BuildContext context) {
        return Dialog(
          insetPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          backgroundColor: Colors.white,
          child: Container(
            constraints: const BoxConstraints(maxWidth: 440),
            padding: EdgeInsets.all(isMobile ? 16 : 24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Align(
                  alignment: Alignment.topRight,
                  child: GestureDetector(
                    onTap: () => Navigator.of(context).pop(),
                    child: Container(
                      padding: const EdgeInsets.all(4),
                      decoration: const BoxDecoration(
                        color: AppColors.secondaryColor,
                        shape: BoxShape.circle,
                      ),
                      child: const Icon(Icons.close, size: 16, color: AppColors.blackColor),
                    ),
                  ),
                ),

                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: 48,
                      height: 48,
                      decoration: BoxDecoration(
                        color: AppColors.emojiBackground,
                        borderRadius: BorderRadius.circular(12),
                      ),
                      alignment: Alignment.center,
                      child: const Text('👍', style: TextStyle(fontSize: 24)),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "Edit Request sent  Sucessfully",
                            style: TTextTheme.h13Style(context).copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.textColor,
                              height: 1.2,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Text(
                            "Congratulation! your edit request has successfully sent to the admin",
                            style: TTextTheme.bodyRegular14(context).copyWith(
                              color: AppColors.secondTextColor,
                              height: 1.3,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
